# Base Docker Compose Configuration
# For development: docker compose -f docker-compose.yml -f docker-compose.dev.yml up
# For production: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  # Frontend Next.js App
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - catlog-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - catlog-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    networks:
      - catlog-network

networks:
  catlog-network:
    driver: bridge
